### ISSUE TITLE
[feature] 향후 개발할 기능 및 업데이트

### ISSUE THREAD

**Issue by badaclockA** [byulhook/byul#14]
### 📄 Description

향후 개발할 기능 및 업데이트 내용들을 tasks안에 적음

### ✅ Tasks

- [x] 커밋 메시지 commmitMessage 주석 처리 필터링
- [x] husky 종속성 제외,  설치 스크립트 추가, lefthook과 husk 호환성 작업 
- [ ] 테스트 코드 작성
- [ ] CI/CD 배포 릴리즈 자동화
- [ ] alias config 기능 추가

**Comment by badaclockA** [comment]
해당 내용은 #31 이슈와 통합이 되었습니다.
