### ISSUE TITLE
[setting] Set up automatic PR and ISSUE labelling and automatic PR contacts with setting github action

### ISSUE THREAD

**Issue by badaclockA** [byulhook/byul#48]
### 📄 Description

Set up a workflow to set up automatic labelling and automatic assignees based on the material in the two links below - https://github.com/marketplace/actions/auto-assign-action - https://github.com/kentaro-m/auto-assign-action

+ We will also do automatic issue labelling - https://github.com/marketplace/actions/assign-me-action

### ✅ Tasks

- [x] Set up automatic labelling 
- [x] Set up automatic assignee settings 
- [x] Publish a PR to the project to test and check it out
