### ISSUE TITLE
[fix] byul 개선 사항 ( byul 커밋 로그 개선, puncycode 모듈 종속성, byul 삭제 편의성)

### ISSUE THREAD

**Issue by badaclockA** [byulhook/byul#74]
## byul 커밋 로그 개선
- 한 번 커밋 할 때마다 로그가 너무 길게 나옴
![](https://i.imgur.com/2ecM4iI.png)

## punycode 모듈 관련 종속성 문제 해결
```bash
(node:106976) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead. (Use `node --trace-deprecation ...` to show where the warning was created)
```

## byul 삭제가 어려움
- byul을 종속성에서 제거해도 훅 스크립트가 남아 있어서 불편함.
### byul 삭제 관련 해결방안
- index.ts를 실행시키는 명령어를 prepare-commit-msg에서 실행시키지 않고, 외부에서 실행하도록하기
- byul.config.json이 삭제되면 해당 스크립트도 실행되지 않게 하기
```bash
❯ git commit -m "test"
node:internal/modules/cjs/loader:1222
  throw err;
  ^

Error: Cannot find module '/home/badac/works/test_magit/node_modules/byul/dist/index.js'
    at Module._resolveFilename (node:internal/modules/cjs/loader:1219:15)
    at Module._load (node:internal/modules/cjs/loader:1045:27)
    at TracingChannel.traceSync (node:diagnostics_channel:315:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:215:24)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:158:5)
    at node:internal/main/run_main_module:30:49 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Node.js v22.5.1
```

### ✅ Tasks

- [x] byul 커밋 로그 개선 
- [x] puncycode 모듈 종속성 문제 해결
- [x]  byul 종속성 제거 이후에는 byul이 아예 실행되지 않게 하기
- [x] husky에서 테스트

**Comment by theconomicat** [comment]
prepare-commit-msg 훅에서 실행이 되는게 아니면 어떤식으로 할 생각이신가요?

**Comment by theconomicat** [comment]
로그는 어떻게 개선하실 생각이신가요?

**Comment by badaclockA** [comment]
> prepare-commit-msg 훅에서 실행이 되는게 아니면 어떤식으로 할 생각이신가요?

### prepare-commit-msg 훅에 들어갈 스크립트를 수정
- prepare-commit-msg에서 실행을 시키는 것은 동일합니다.
- byul 종속성이 node_modules에서 제거된 경우 byul이 아예 작동이 되지 않게 할 수 있습니다.
- 아래의 코드에서 find_module() 함수는 node_modules, package.json에서 byul이 제거되었는지를 확인하고 만약에 제거되었다면 아무것도 실행을 하지 않습니다.
- 사용자가 기존에 prepare-commit-msg 훅을 사용중이였다면 상단에 스크립트를 명시하게 해서  byul 스크립트의 실행과 상관없이 실행되게 할 수 있습니다



```
#!/usr/bin/env bash

# -----다른 훅 스크립트------
echo "running other prepare-commit-msg hooks!"
echo "다른 스크립트들은 여기서 실행 가능"
# --------------------------

MODULE_NAME="lefthook"

PROJECT_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || echo ".")

find_module() {
    if [ -d "$PROJECT_ROOT/node_modules/$MODULE_NAME" ]; then
        return 0
    fi

    if grep -q "\"$MODULE_NAME\"" "$PROJECT_ROOT/package.json" 2>/dev/null; then
        return 0
    fi

    if command -v $MODULE_NAME >/dev/null 2>&1; then
        return 0
    fi

    return 1
}

if find_module; then
# ----------- byul 스크립트 실행 ------------------
    node dist/index.js "$1" "$2" "$3" 
# -----------------------------
else
    :
fi

exit 0
```

**Comment by badaclockA** [comment]
> 로그는 어떻게 개선하실 생각이신가요?

AI:false인 경우에만 수정할 것입니다. AI 커밋 모드가 아닐 때는 이렇게 긴 로그가 출력 될 필요가 없으니 저 빨간색 사각형 부분들을 1,2줄로 로그로 줄일 예정임.
![image](https://github.com/user-attachments/assets/9f96b70b-c8ab-431c-a5ee-17c489432573)

**Comment by theconomicat** [comment]
오 좋네요
