### ISSUE TITLE
[test] byul v2 테스트 계획

### ISSUE THREAD

**Issue by badaclockA** [byulhook/byul#85]
### 📄 Description

다음 버전 부터는 테스팅 이후에 배포가 이루어지도록 할 것 같습니다. 

1. github action을 이용한 다양한 운영체제 환경 테스틩
저희 프로젝트 특성상 window11, ubuntu, macOS 환경에서 필요합니다.
 github action은 다양한 환경 os에서 테스팅이 가능하기 때문에 이용할 예정입니다.

2. jest를 이용한 유닛테스트
jest를 이용하여 각 함수들의 인풋, 아웃풋을 테스팅을 할 예정입니다. 동시에 공통된 기능들에 대해서 리팩토링과 함수리네이밍을 진행할 예정입니다. 

### ✅ Tasks

- [ ] github action 테스팅 환경 구성하기
- [ ] setup.mjs 테스팅
- [ ] index.ts 테스팅
